apiVersion: v1
kind: Service
metadata:
  name: simple-chat-service
spec:
  selector:
    app: simple-chat
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007